### ISSUE TITLE
치카VPN 브랜드 이름 경고

### ISSUE THREAD

**Issue by HaswellAoba** [3MP404/NetclassKiller#2]
치카VPN 선린지역공급업체 한국에반스전자(주)에서 인사드립니다.

당사 상표와 관련하여 Issue를 제시합니다.

당사 서비스의 정식 명칭은 "Evans ChikaVPN" 또는 "Evans 치카VPN"이며, 따라서 귀하의 Script로 VPN을 등록할 때 "chika.kr" 이름으로 등록이 되는 것이 아닌 당사 공식 명칭으로 등록되기를 희망합니다.

당사 서비스가 귀하의 소프트웨어에 탑재되어 공급되는 것은 매우 환영할 일이나 상표권을 지켜 주셨으면 합니다.

참고해 주시고 가능한 한 빠른 시일 이내에 답변해 주십시오. 어떤 문의 사항이 있는 경우 당사 고객센터로 문의하십시오.

감사합니다.
한국에반스전자 클라우드사업본부

**Comment by samidare20** [comment]
이번 commit에서 vpn 이름을 Evans_ChikaVPN으로 생성하도록 수정하였습니다.
